---
- name: Reset password for users
  hosts: test1
#  vars:
#    users:
#    - tomas
#    - adi
  vars_prompt:
  - name: USERNAME
    prompt: what is the username you wish to reset his password ?
    private: no
  - name: NEW_PASSWORD
    prompt: What is the new password
    private: no
  tasks:
  - name: Reset Password
    user:
      name: "{{ USERNAME }}"
      password: "{{ NEW_PASSWORD | password_hash ('sha512') }}"
   
