---
- name: Reset password for users
  hosts: test1
  vars_prompt:
  - name: USERNAME
    prompt: what is the username you wish to reset his password ?
    private: no
  - name: NEW_PASSWORD
    prompt: What is the new password
    private: no
  tasks:
  - name: Reset Password
    user:
      name: "{{ USERNAME }}"
      password: "{{ NEW_PASSWORD | password_hash ('sha512') }}"
   
# This playbook will prompt you to type the user name you want to change password and will
# prompt you to type the password for the user and it will be hashed and not plain text.
